apiVersion: v1
kind: Namespace
metadata:
  name: onlineboutique
  labels:
    istio.io/rev: asm-192-1
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
