apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
kind: Endpoints
apiVersion: v1
metadata:
 name: redis-cart
subsets:
 - addresses:
     - ip: 10.8.52.19
   ports:
     - port: 6379