apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
kind: Endpoints
apiVersion: v1
metadata:
 name: redis-cart
subsets:
 - addresses:
     - ip: 10.191.193.59
   ports:
     - port: 6379
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-cart
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: redis-cart
  updatePolicy:
    updateMode: "Off"