apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: myblog
  namespace: myblog
spec:
  selector:
    matchLabels:
      app: myblog
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/asm-ingress/sa/asm-ingressgateway
    to:
    - operation:
        methods:
        - GET
        ports:
        - "8080"