apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: myblog
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: myblog
  updatePolicy:
    updateMode: "Off"