apiVersion: v1
kind: ServiceAccount
metadata:
  name: balancereader
  annotations:
    iam.gke.io/gcp-service-account: bankofanthos-gsa@mygke-200.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancereader
spec:
  selector:
    matchLabels:
      app: balancereader
  template:
    metadata:
      labels:
        app: balancereader
    spec:
      serviceAccountName: balancereader
      terminationGracePeriodSeconds: 5
      containers:
      - name: balancereader
        image: us-east4-docker.pkg.dev/mygke-200/containers/bank-of-anthos/balancereader:v0.5.2
        volumeMounts:
        - name: publickey
          mountPath: "/root/.ssh"
          readOnly: true
        env:
        - name: VERSION
          value: "v0.5.1"
        - name: PORT
          value: "8080"
        # toggle Cloud Trace export
        - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "true"
        - name: POLL_MS
          value: "100"
        - name: CACHE_SIZE
          value: "1000000"
        # tell Java to obey container memory limits
        - name: JVM_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        # Valid levels are debug, info, warn, error, fatal.
        # If no valid level is set, will default to info.
        - name: LOG_LEVEL
          value: "info"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: environment-config
        # add ledger-db credentials from ConfigMap
        - configMapRef:
            name: ledger-db-config
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 10
      volumes:
      - name: publickey
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key.pub
            path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: balancereader
spec:
  type: ClusterIP
  selector:
    app: balancereader
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: balancereader
spec:
  selector:
    matchLabels:
      app: balancereader
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/bankofanthos/sa/frontend", "cluster.local/ns/bankofanthos/sa/ledgerwriter"]
    to:
      - operation:
          paths: ["/balances/*"]
          methods: ["GET"]
          ports: ["8080"]
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: balancereader
spec:
  workloadSelector:
    labels:
      app: balancereader
  egress:
  - hosts:
    - "istio-system/*"
    - "./ledger-db.bankofanthos.svc.cluster.local"