apiVersion: v1
kind: ServiceAccount
metadata:
  name: contacts
  annotations:
    iam.gke.io/gcp-service-account: bankofanthos-gsa@mygke-200.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      serviceAccountName: contacts
      terminationGracePeriodSeconds: 5
      containers:
      - name: contacts
        image: us-east4-docker.pkg.dev/mygke-200/containers/bank-of-anthos/contacts:v0.5.4
        volumeMounts:
        - name: publickey
          mountPath: "/root/.ssh"
          readOnly: true
        env:
        - name: VERSION
          value: "v0.5.4"
        - name: PORT
          value: "8080"
        - name: ENABLE_TRACING
          value: "false"
        # Valid levels are debug, info, warning, error, critical.
        # If no valid level is set, will default to info.
        - name: LOG_LEVEL
          value: "info"
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: accounts-db-config
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
      volumes:
      - name: publickey
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key.pub
            path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: contacts
spec:
  type: ClusterIP
  selector:
    app: contacts
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: contacts
spec:
  selector:
    matchLabels:
      app: contacts
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/bankofanthos/sa/frontend"]
    to:
      - operation:
          paths: ["/contacts/*"]
          methods: ["GET"]
          ports: ["8080"]
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: contacts
spec:
  workloadSelector:
    labels:
      app: contacts
  egress:
  - hosts:
    - "istio-system/*"
    - "./accounts-db.bankofanthos.svc.cluster.local"