apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-db
  annotations:
    iam.gke.io/gcp-service-account: bankofanthos-gsa@mygke-200.iam.gserviceaccount.com
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ledger-db
spec:
  serviceName: "ledger-db"
  replicas: 1
  selector:
    matchLabels:
      app: ledger-db
  template:
    metadata:
      labels:
        app: ledger-db
    spec:
      serviceAccountName: ledger-db
      containers:
        - name: postgres
          image: us-east4-docker.pkg.dev/mygke-200/containers/bank-of-anthos/ledger-db:v0.5.1
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: ledger-db-config
            - configMapRef:
                name: demo-data-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgresdb
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: password # should match POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ledger-db
spec:
  selector:
    matchLabels:
      app: ledger-db
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/bankofanthos/sa/balancereader", "cluster.local/ns/bankofanthos/sa/transactionhistory", "cluster.local/ns/bankofanthos/sa/ledgerwriter"]
    to:
      - operation:
          ports: ["5432"]
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: ledger-db
spec:
  workloadSelector:
    labels:
      app: ledger-db
  egress:
  - hosts:
    - "istio-system/*"