apiVersion: v1
kind: ServiceAccount
metadata:
  name: userservice
  annotations:
    iam.gke.io/gcp-service-account: bankofanthos-gsa@mygke-200.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      serviceAccountName: userservice
      terminationGracePeriodSeconds: 5
      containers:
      - name: userservice
        image: us-east4-docker.pkg.dev/mygke-200/containers/bank-of-anthos/userservice:v0.5.1
        volumeMounts:
        - name: keys
          mountPath: "/root/.ssh"
          readOnly: true
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: VERSION
          value: "v0.5.0"
        - name: PORT
          value: "8080"
        - name: ENABLE_TRACING
          value: "false"
        - name: TOKEN_EXPIRY_SECONDS
          value: "3600"
        - name: PRIV_KEY_PATH
          value: "/root/.ssh/privatekey"
         # Valid levels are debug, info, warning, error, critical. If no valid level is set, defaults to info.
        - name: LOG_LEVEL
          value: "info"
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: accounts-db-config
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: keys
        secret:
          secretName: jwt-key
          items:
          - key: jwtRS256.key
            path: privatekey
          - key: jwtRS256.key.pub
            path: publickey
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/bankofanthos/sa/frontend"]
    to:
      - operation:
          paths: ["/users", "/login"]
          methods: ["GET", "POST"]
          ports: ["8080"]
---
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: userservice
spec:
  workloadSelector:
    labels:
      app: userservice
  egress:
  - hosts:
    - "istio-system/*"
    - "./accounts-db.bankofanthos.svc.cluster.local"