apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: currency
spec:
  hosts:
    - www.ecb.europa.eu
  http:
  - timeout: 3s
    route:
      - destination:
          host: www.ecb.europa.eu
        weight: 100