apiVersion: v1
kind: Namespace
metadata:
  name: dotnet
  labels:
    istio.io/rev: asm-183-2
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: denyall
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress