apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  labels:
    app: web
  name: web
spec:
  backend:
    serviceName: web
    servicePort: 8080