apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: asm-ingressgateway
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP
  securityPolicy:
    name: mygke-asm-ingressgateway