apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: asm-ingressgateway
spec:
  sslPolicy: mygke-asm-ingressgateway
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT