apiVersion: v1
kind: Namespace
metadata:
  name: asm-ingress
  labels:
    name: asm-ingress # for NetworkPolicies
    istio.io/rev: asm-1112-17
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT