apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: denyall
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: asm-ingressgateway
spec:
  podSelector:
    matchLabels:
      app: asm-ingressgateway
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: myblog-light
      podSelector:
        matchLabels:
          app: myblog
    ports:
     - port: 8080
       protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          name: myblog
      podSelector:
        matchLabels:
          app: myblog
    ports:
     - port: 8080
       protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          name: onlineboutique
      podSelector:
        matchLabels:
          app: frontend
    ports:
     - port: 8080
       protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          name: bankofanthos
      podSelector:
        matchLabels:
          app: frontend
    ports:
     - port: 8080
       protocol: TCP