name: ci-myblog

on:
  push:
    branches: [ main ]
    paths:
    - namespaces/myblog/*
    - .github/workflows/ci-myblog.yml
  pull_request:
    branches: [ main ]
    paths:
    - namespaces/myblog/*
    - .github/workflows/ci-myblog.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd namespaces
          docker run \
            -v `pwd`/myblog:/myblog garethr/kubeval \
            --strict \
            --skip-kinds VerticalPodAutoscaler,ManagedCertificate \
            myblog/*
      - name: Run conftest for OPA regos on Kubernetes manifests	
        run: |	
          cd namespaces/myblog
          mkdir policy	
          curl https://raw.githubusercontent.com/mathieu-benoit/mygkecluster/master/policy/kubernetes-policies.rego -o ./policy/kubernetes-policies.rego	
          docker run --rm -v $(pwd):/project openpolicyagent/conftest test .