name: ci-onlineboutique

on:
  push:
    branches: [ main ]
    paths:
    - namespaces/onlineboutique/*
    - .github/workflows/ci-onlineboutique.yml
  pull_request:
    branches: [ main ]
    paths:
    - namespaces/onlineboutique/*
    - .github/workflows/ci-onlineboutique.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          cd namespaces
          docker run \
            -v `pwd`/onlineboutique:/onlineboutique garethr/kubeval \
            --strict \
            --skip-kinds VerticalPodAutoscaler,ServiceEntry,VirtualService,Gateway,DestinationRule \
            onlineboutique/*
