name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dehydrate the kubernetes manifests	
        run: |	
          gsutil cp gs://config-management-release/released/latest/linux_amd64/nomos nomos
          chmod +x nomos
          mkdir tmp
          ./nomos hydrate --flat --no-api-server-check --output tmp/hydrated-manifests.yaml
      - name: test opa gatekeeper constraints against kubernetes manifests
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.8/kpt_linux_amd64 -o kpt
          chmod +x kpt
          ./kpt fn eval --image gcr.io/kpt-fn/gatekeeper:v0.2 tmp/
      
