name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.1
      - name: install kpt and nomos	
        run: |
          gcloud components install kpt nomos --quiet
      - name: vet	
        run: |
          nomos vet --no-api-server-check
      - name: hydration	
        run: |
          mkdir tmp
          nomos hydrate --flat --no-api-server-check --output tmp/hydrated-manifests.yaml
      - name: kubeval
        run: |
          kpt fn eval tmp --image gcr.io/kpt-fn/kubeval:v0.2 -- strict=true ignore_missing_schemas=true
      - name: gatekeeper
        run: |
          kpt fn eval --image gcr.io/kpt-fn/gatekeeper:v0.2 tmp/
      - name: analyze
        run: |
          curl -sL https://istio.io/downloadIstioctl | sh -
          $HOME/.istioctl/bin/istioctl analyze tmp/hydrated-manifests.yaml --use-kube=false -v
